/* Copyright (c) 2026 Nenad Mićić <nenad@micic.be>
 * SPDX-License-Identifier: Apache-2.0 */
/*
 * kt_wheel.c - admissibility-wheel CRT-join builder (Phase 3b).
 *
 * Pure C (compiles with cc -O3 -std=c11). See kt_wheel.h for the API.
 *
 * Algorithm follows the project's CRT-join wheel model:
 *   For each q in prime_list:
 *     immune = [0..q-1] \ F_q
 *     if |immune| == 0: pattern inadmissible at q -> return -2
 *     wheel = CRT-extend(wheel, m, q, immune)   (sorted, deduped)
 *     m *= q
 *   FNV-1a-64 the final sorted offsets to detect drift vs GP canonical.
 *
 * The kt_canonical_wheel_hashes[] table at the bottom of this file is the
 * ground truth, regenerated by `make canonical-hashes` from the self-contained
 * GP parity tool.
 */

#include "kt_wheel.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>

/* ─────────────────────────────────────────────────────────────────────────── */
/* Forbidden residue set: F_q = { (q - (b_i mod q)) mod q }, deduped.        */
/* Mirrors gp/kt_lib_v1.gp:kt_pattern_forbidden line 55.                      */
/* ─────────────────────────────────────────────────────────────────────────── */
int kt_wheel_pattern_forbidden(const uint32_t *pat, int k, uint32_t q,
                               uint32_t *out_forbidden) {
    if (!pat || !out_forbidden || k <= 0 || q == 0) return 0;
    int count = 0;
    for (int i = 0; i < k; i++) {
        uint32_t r = (q - (pat[i] % q)) % q;
        int dup = 0;
        for (int j = 0; j < count; j++) {
            if (out_forbidden[j] == r) { dup = 1; break; }
        }
        if (!dup) out_forbidden[count++] = r;
    }
    return count;
}

/* Extended Euclid: returns gcd; writes Bezout coefficients to *x,*y. */
static int64_t egcd_i64(int64_t a, int64_t b, int64_t *x, int64_t *y) {
    if (b == 0) { *x = 1; *y = 0; return a; }
    int64_t x1, y1;
    int64_t g = egcd_i64(b, a % b, &x1, &y1);
    *x = y1;
    *y = x1 - (a / b) * y1;
    return g;
}

/* Modular inverse of a mod q (q prime, gcd(a,q)=1). Returns value in [0,q). */
static uint32_t mod_inv_u32(uint32_t a, uint32_t q) {
    int64_t x, y;
    (void)egcd_i64((int64_t)a, (int64_t)q, &x, &y);
    int64_t r = x % (int64_t)q;
    if (r < 0) r += (int64_t)q;
    return (uint32_t)r;
}

static int cmp_u64(const void *pa, const void *pb) {
    uint64_t a = *(const uint64_t *)pa;
    uint64_t b = *(const uint64_t *)pb;
    if (a < b) return -1;
    if (a > b) return  1;
    return 0;
}

/* CRT-extend: given a wheel (sorted residues) mod m and immune residues mod q
 * (q coprime to m), produce a sorted/deduped wheel mod m*q in `out`.
 *
 *   x = a + m * ((b - a) * m^{-1} mod q)        (in [0, m*q))
 *
 * Returns new count, or -1 on capacity overflow, -3 on m*q overflowing u64. */
static int wheel_extend(const uint64_t *wheel, int wheel_count,
                        uint64_t m, uint32_t q,
                        const uint32_t *immune, int immune_count,
                        uint64_t *out, int out_max) {
    if (q == 0) return -2;
    __uint128_t mq128 = (__uint128_t)m * (__uint128_t)q;
    if (mq128 > (__uint128_t)UINT64_MAX) return -3;

    /* m^{-1} mod q. Use m mod q so the inverse argument is in [0,q). */
    uint32_t m_mod_q = (uint32_t)(m % (uint64_t)q);
    if (m_mod_q == 0) return -2;     /* q not coprime to m */
    uint32_t m_inv = mod_inv_u32(m_mod_q, q);

    int64_t cap_needed = (int64_t)wheel_count * (int64_t)immune_count;
    if (cap_needed > (int64_t)out_max) return -1;

    int n = 0;
    for (int i = 0; i < wheel_count; i++) {
        uint64_t a = wheel[i];
        uint32_t a_mod_q = (uint32_t)(a % (uint64_t)q);
        for (int j = 0; j < immune_count; j++) {
            uint32_t b = immune[j];
            uint32_t bma = (b + q - a_mod_q) % q;
            uint64_t kk  = ((uint64_t)bma * (uint64_t)m_inv) % (uint64_t)q;
            /* x = a + m*kk. a < m, kk < q, so x < m*q (no u64 overflow). */
            uint64_t x = a + m * kk;
            out[n++] = x;
        }
    }

    qsort(out, (size_t)n, sizeof(uint64_t), cmp_u64);
    int w = 0;
    for (int i = 0; i < n; i++) {
        if (i == 0 || out[i] != out[i - 1]) out[w++] = out[i];
    }
    return w;
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* Phase 3c forbidden-mask helpers.                                           */
/* All three forms iterate the pattern, compute r = (q - (b_i % q)) % q, and  */
/* set the bit at residue r. Mirrors kt_wheel_pattern_forbidden but emits the */
/* mask directly (no dedup buffer needed since OR is idempotent).             */
/* ─────────────────────────────────────────────────────────────────────────── */
uint64_t kt_forbidden_mask_u64(const uint32_t *pat, int k, uint32_t q) {
    if (!pat || k <= 0 || q == 0 || q >= 64) return 0;
    uint64_t m = 0;
    for (int i = 0; i < k; i++) {
        uint32_t r = (q - (pat[i] % q)) % q;
        m |= (uint64_t)1 << r;
    }
    return m;
}

void kt_forbidden_mask_u128(const uint32_t *pat, int k, uint32_t q,
                            uint64_t *lo, uint64_t *hi) {
    if (!lo || !hi) return;
    *lo = 0;
    *hi = 0;
    if (!pat || k <= 0 || q == 0 || q >= 128) return;
    for (int i = 0; i < k; i++) {
        uint32_t r = (q - (pat[i] % q)) % q;
        if (r < 64) *lo |= (uint64_t)1 << r;
        else        *hi |= (uint64_t)1 << (r - 64);
    }
}

void kt_forbidden_mask_packed(const uint32_t *pat, int k, uint32_t q,
                              uint64_t *out, int words) {
    if (!out || words <= 0) return;
    for (int i = 0; i < words; i++) out[i] = 0;
    if (!pat || k <= 0 || q == 0) return;
    uint32_t cap = (uint32_t)words * 64u;
    if (q > cap) return;
    for (int i = 0; i < k; i++) {
        uint32_t r = (q - (pat[i] % q)) % q;
        out[r >> 6] |= (uint64_t)1 << (r & 63u);
    }
}

/* FNV-1a-64 over u64 array (8 little-endian bytes per element). */
uint64_t kt_wheel_fnv1a64_u64_array(const uint64_t *arr, int n) {
    uint64_t h = 0xcbf29ce484222325ULL;
    const uint64_t prime = 0x100000001b3ULL;
    for (int i = 0; i < n; i++) {
        uint64_t v = arr[i];
        for (int b = 0; b < 8; b++) {
            uint8_t byte = (uint8_t)((v >> (8 * b)) & 0xff);
            h ^= (uint64_t)byte;
            h *= prime;
        }
    }
    return h;
}

void kt_wheel_free(kt_wheel_t *w) {
    if (!w) return;
    free(w->offsets);
    w->offsets = NULL;
    w->n_admissible = 0;
}

static void kt_wheel_expr_err(char *err, size_t err_len, const char *msg) {
    if (!err || err_len == 0) return;
    snprintf(err, err_len, "%s", msg ? msg : "invalid wheel expression");
}

static int kt_wheel_catalog_index(const uint32_t *catalog, int n, uint32_t p) {
    if (!catalog || n <= 0) return -1;
    for (int i = 0; i < n; i++) {
        if (catalog[i] == p) return i;
    }
    return -1;
}

static int kt_wheel_parse_u32_token(const char **pp, uint32_t *out) {
    if (!pp || !*pp || !out) return -1;
    const char *p = *pp;
    if (*p < '0' || *p > '9') return -1;
    errno = 0;
    char *end = NULL;
    unsigned long v = strtoul(p, &end, 10);
    if (end == p || errno == ERANGE || v > UINT_MAX) return -1;
    *out = (uint32_t)v;
    *pp = end;
    return 0;
}

int kt_wheel_parse_expr(const char *expr,
                        const uint32_t *prime_catalog, int catalog_n,
                        uint32_t *out_primes, int *out_n_primes,
                        int *out_ceiling_idx,
                        char *out_canon, size_t out_canon_len,
                        char *err, size_t err_len) {
    if (out_n_primes) *out_n_primes = 0;
    if (out_ceiling_idx) *out_ceiling_idx = -1;
    if (out_canon && out_canon_len > 0) out_canon[0] = '\0';
    if (!expr || !*expr || !prime_catalog || catalog_n <= 0 ||
        !out_primes || !out_n_primes || !out_ceiling_idx) {
        kt_wheel_expr_err(err, err_len, "missing wheel expression or output buffer");
        return -1;
    }
    if (catalog_n > KT_WHEEL_EXPR_MAX_PRIMES) {
        kt_wheel_expr_err(err, err_len, "prime catalog exceeds wheel-expression limit");
        return -1;
    }

    const char *p = expr;
    uint32_t ceiling = 0;
    if (kt_wheel_parse_u32_token(&p, &ceiling) != 0 || *p != '#') {
        kt_wheel_expr_err(err, err_len, "expected wheel expression like X# or X#/Y/Z");
        return -1;
    }
    p++; /* '#' */

    int ceiling_idx = kt_wheel_catalog_index(prime_catalog, catalog_n, ceiling);
    if (ceiling_idx < 0) {
        kt_wheel_expr_err(err, err_len, "wheel ceiling X is not in the supported prime catalog");
        return -1;
    }

    int drop[KT_WHEEL_EXPR_MAX_PRIMES];
    for (int i = 0; i < KT_WHEEL_EXPR_MAX_PRIMES; i++) drop[i] = 0;

    while (*p) {
        if (*p != '/') {
            kt_wheel_expr_err(err, err_len, "expected '/' before dropped prime");
            return -1;
        }
        p++;
        uint32_t d = 0;
        if (kt_wheel_parse_u32_token(&p, &d) != 0) {
            kt_wheel_expr_err(err, err_len, "bad dropped-prime token");
            return -1;
        }
        int d_idx = kt_wheel_catalog_index(prime_catalog, catalog_n, d);
        if (d_idx < 0 || d_idx >= ceiling_idx) {
            kt_wheel_expr_err(err, err_len, "dropped prime must be in X# and below X");
            return -1;
        }
        if (drop[d_idx]) {
            kt_wheel_expr_err(err, err_len, "dropped prime appears more than once");
            return -1;
        }
        drop[d_idx] = 1;
    }

    int n = 0;
    __uint128_t product = 1;
    for (int i = 0; i <= ceiling_idx; i++) {
        if (drop[i]) continue;
        product *= (__uint128_t)prime_catalog[i];
        if (product > (__uint128_t)UINT64_MAX) {
            kt_wheel_expr_err(err, err_len, "wheel modulus overflows u64");
            return -1;
        }
        out_primes[n++] = prime_catalog[i];
    }
    if (n <= 0) {
        kt_wheel_expr_err(err, err_len, "wheel expression drops every prime");
        return -1;
    }

    if (out_canon && out_canon_len > 0) {
        int wrote = snprintf(out_canon, out_canon_len, "%u#", ceiling);
        if (wrote < 0 || (size_t)wrote >= out_canon_len) {
            kt_wheel_expr_err(err, err_len, "canonical wheel expression buffer too small");
            return -1;
        }
        size_t used = (size_t)wrote;
        for (int i = 0; i <= ceiling_idx; i++) {
            if (!drop[i]) continue;
            wrote = snprintf(out_canon + used, out_canon_len - used,
                             "/%u", prime_catalog[i]);
            if (wrote < 0 || (size_t)wrote >= out_canon_len - used) {
                kt_wheel_expr_err(err, err_len, "canonical wheel expression buffer too small");
                return -1;
            }
            used += (size_t)wrote;
        }
    }

    *out_n_primes = n;
    *out_ceiling_idx = ceiling_idx;
    kt_wheel_expr_err(err, err_len, "");
    return 0;
}

int kt_wheel_crt_join(const uint32_t *pat, int k,
                      const uint32_t *prime_list, int n_primes,
                      kt_wheel_t *out) {
    if (!pat || !prime_list || !out || k <= 0 || n_primes <= 0) return -1;
    out->offsets      = NULL;
    out->n_admissible = 0;
    out->primorial    = 1;
    out->fnv1a64_hash = 0;

    /* Two heap buffers; ping-pong. wheel starts as [0] mod 1. */
    uint64_t *cur  = (uint64_t *)malloc((size_t)KT_WHEEL_MAX_ADMISSIBLE * sizeof(uint64_t));
    uint64_t *next = (uint64_t *)malloc((size_t)KT_WHEEL_MAX_ADMISSIBLE * sizeof(uint64_t));
    if (!cur || !next) { free(cur); free(next); return -4; }

    int cur_n = 1;
    cur[0] = 0;
    uint64_t m = 1;

    uint32_t fbd[64];           /* k <= KT_MAX_K = 32; safe */
    uint32_t immune[64];

    for (int p = 0; p < n_primes; p++) {
        uint32_t q = prime_list[p];
        if (q < 2) { free(cur); free(next); return -2; }

        int n_fbd = kt_wheel_pattern_forbidden(pat, k, q, fbd);
        if (n_fbd >= (int)q) { free(cur); free(next); return -2; }

        int n_imm = 0;
        for (uint32_t r = 0; r < q; r++) {
            int is_fbd = 0;
            for (int j = 0; j < n_fbd; j++) if (fbd[j] == r) { is_fbd = 1; break; }
            if (!is_fbd) immune[n_imm++] = r;
        }
        if (n_imm == 0) { free(cur); free(next); return -2; }

        int rc = wheel_extend(cur, cur_n, m, q, immune, n_imm,
                              next, KT_WHEEL_MAX_ADMISSIBLE);
        if (rc < 0) { free(cur); free(next); return rc; }

        uint64_t *tmp = cur; cur = next; next = tmp;
        cur_n = rc;

        __uint128_t mq = (__uint128_t)m * (__uint128_t)q;
        if (mq > (__uint128_t)UINT64_MAX) { free(cur); free(next); return -3; }
        m = (uint64_t)mq;
    }

    /* Trim cur down to its actual size and hand off to caller. */
    uint64_t *final_buf = (uint64_t *)malloc((size_t)cur_n * sizeof(uint64_t));
    if (!final_buf) { free(cur); free(next); return -4; }
    memcpy(final_buf, cur, (size_t)cur_n * sizeof(uint64_t));
    free(cur);
    free(next);

    out->primorial    = m;
    out->n_admissible = cur_n;
    out->offsets      = final_buf;
    out->fnv1a64_hash = kt_wheel_fnv1a64_u64_array(final_buf, cur_n);
    return 0;
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* Phase 9 T2.1: streaming CRT-join wheel construction for 41#/43#/47#.       */
/*                                                                            */
/* The Phase 3 kt_wheel_crt_join() above allocates two ping-pong buffers each */
/* sized to KT_WHEEL_MAX_ADMISSIBLE = 1 MiB entries.  At 41#+ wheels for      */
/* low-k wide patterns (KT19_P0 lifts to ~5.85M @ 41#, ~140M @ 43#, ~3.9G @  */
/* 47#) that fixed cap is hopelessly small.                                   */
/*                                                                            */
/* Implementation:                                                            */
/*  1. Predict per-step sizes from prime_list and pattern's |F_q| for each q. */
/*  2. Track cumulative peak (cur + next u64 buffers).                        */
/*  3. Abort early if final_size or peak exceeds max_bytes (4 GiB cap).       */
/*  4. Per-step allocate `next` exactly sized for that step's output, run    */
/*     wheel_extend, free old `cur`, swap.                                    */
/*                                                                            */
/* Returns the same kt_wheel_t shape as kt_wheel_crt_join.  The cap-overflow  */
/* path returns -1 with peak_bytes_out written for diagnostic logging.        */
/* ─────────────────────────────────────────────────────────────────────────── */
int kt_wheel_crt_join_streaming(const uint32_t *pat, int k,
                                const uint32_t *prime_list, int n_primes,
                                size_t max_bytes,
                                size_t *peak_bytes_out,
                                kt_wheel_t *out) {
    if (peak_bytes_out) *peak_bytes_out = 0;
    if (!pat || !prime_list || !out || k <= 0 || n_primes <= 0) return -1;
    out->offsets      = NULL;
    out->n_admissible = 0;
    out->primorial    = 1;
    out->fnv1a64_hash = 0;

    /* Step 1: predict per-step admissible counts and primorial product.
     * size_per_step[i] = size after lifting through prime_list[0..i].
     * The lift rule from CRT-join is:
     *   |A_{Pq}| = |A_P| × (q - |F_q|)
     * where F_q = pattern's forbidden residue set at q (|F_q| < q for
     * an admissible pattern). */
    if (n_primes > 64) return -1;       /* sanity */
    size_t size_after[65];               /* size_after[0] = 1 (initial [0] mod 1) */
    size_after[0] = 1;
    __uint128_t primorial128 = 1;
    {
        uint32_t fbd[64];
        for (int p = 0; p < n_primes; p++) {
            uint32_t q = prime_list[p];
            if (q < 2) return -2;
            int n_fbd = kt_wheel_pattern_forbidden(pat, k, q, fbd);
            if (n_fbd >= (int)q) return -2;
            size_after[p + 1] = size_after[p] * (size_t)(q - (uint32_t)n_fbd);
            __uint128_t mq = primorial128 * (__uint128_t)q;
            if (mq > (__uint128_t)UINT64_MAX) return -3;
            primorial128 = mq;
        }
    }
    size_t final_size  = size_after[n_primes];
    size_t final_bytes = final_size * sizeof(uint64_t);

    /* Peak intermediate alloc: at step i we hold cur (size_after[i]) AND the
     * freshly allocated next (size_after[i+1]); cur is freed immediately
     * after wheel_extend returns.  The final buffer reuses the last `next`
     * directly — no trim copy — because for distinct primes wheel_extend's
     * dedup is a no-op and the allocation is exactly sized. */
    size_t peak_bytes = 0;
    for (int i = 0; i < n_primes; i++) {
        size_t s = (size_after[i] + size_after[i + 1]) * sizeof(uint64_t);
        if (s > peak_bytes) peak_bytes = s;
    }
    if (peak_bytes_out) *peak_bytes_out = peak_bytes;
    (void)final_bytes;

    if (peak_bytes > max_bytes) return -1;

    /* Initial wheel: [0] mod 1.  size_after[0] = 1. */
    uint64_t *cur = (uint64_t *)malloc(1 * sizeof(uint64_t));
    if (!cur) return -4;
    cur[0] = 0;
    size_t cur_n = 1;
    uint64_t m = 1;

    uint32_t fbd[64];
    uint32_t immune[256];               /* worst case q ≤ 47 → ≤47 immune residues */

    for (int p = 0; p < n_primes; p++) {
        uint32_t q = prime_list[p];
        int n_fbd = kt_wheel_pattern_forbidden(pat, k, q, fbd);
        int n_imm = 0;
        for (uint32_t r = 0; r < q; r++) {
            int is_fbd = 0;
            for (int j = 0; j < n_fbd; j++) if (fbd[j] == r) { is_fbd = 1; break; }
            if (!is_fbd && n_imm < (int)(sizeof(immune) / sizeof(immune[0])))
                immune[n_imm++] = r;
        }
        if (n_imm == 0) { free(cur); return -2; }

        /* Allocate next at exactly the predicted size for this step. */
        size_t next_capacity = size_after[p + 1];
        if (next_capacity > (size_t)INT32_MAX) {
            /* wheel_extend uses int for cap; refuse rather than truncate.
             *
             * Known limitation: this hard-caps K=19 / 47# (predicted ~4B
             * residues = 31 GiB at 8 B/residue) even when the host-RAM
             * cap (kt_filter_v8.cu MAX_BYTES) is set wide enough. K=20
             * (1.6B residues, 12.7 GiB) and K=21 (1.2B, 9.3 GiB) fit.
             * Lifting this requires int -> int64_t plumbing through
             * wheel_extend, kt_wheel_t::n_admissible, and any GPU sieve
             * kernel that takes the residue count as an int launch
             * parameter (a flat 1-D grid > INT32_MAX overflows
             * gridDim.x * blockDim.x; need 2-D grid or chunked launch).
             * Verified during the 2026-05-10 wheel-comparison campaign. */
            free(cur);
            return -1;
        }
        uint64_t *next = (uint64_t *)malloc(next_capacity * sizeof(uint64_t));
        if (!next) { free(cur); return -4; }

        int rc = wheel_extend(cur, (int)cur_n, m, q, immune, n_imm,
                              next, (int)next_capacity);
        if (rc < 0) { free(cur); free(next); return rc; }

        free(cur);
        cur   = next;
        cur_n = (size_t)rc;
        __uint128_t mq = (__uint128_t)m * (__uint128_t)q;
        m = (uint64_t)mq;
    }

    /* Hand off cur directly: it was allocated at exactly size_after[n_primes]
     * and (for distinct primes) wheel_extend's dedup is a no-op so cur_n
     * equals that capacity.  Skipping the trim copy keeps peak alloc at
     * (cur+next) max rather than (cur+final). */
    out->primorial    = m;
    out->n_admissible = (int)cur_n;
    out->offsets      = cur;
    out->fnv1a64_hash = kt_wheel_fnv1a64_u64_array(cur, (int)cur_n);
    return 0;
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* Canonical-hash table.                                                      */
/* Generated by `make canonical-hashes` (tools/dump_wheel_canonical_hash.gp). */
/* PASTE-IN starts here; do not edit by hand.                                 */
/*                                                                            */
/* Note: the brief estimated ~2560 admissible offsets at 37# for narrow       */
/* k>=19 patterns; the actual GP-canonical counts are ~266k for KT19_P0 and   */
/* ~20k for KT22_P0. These are reported as the real numbers per the brief's   */
/* T7 instruction (canonical may have been wrong; do not auto-correct).       */
/* ─────────────────────────────────────────────────────────────────────────── */

const kt_canonical_wheel_t kt_canonical_wheel_hashes[] = {
    { "KT5_P0",   5, {2,3,5,7,11},                        12, 0xe4ab140c4a0b8ca4ULL },
    { "KT9_P0",   5, {2,3,5,7,11},                         3, 0x9e49b4bc5a6e423aULL },
    { "KT17_P0",  6, {2,3,5,7,11,13},                      2, 0x415979a40555a67aULL },
    { "KT19_P0",  6, {2,3,5,7,11,13},                      1, 0x9cfd5795e071b9f4ULL },
    { "KT19_P0", 12, {2,3,5,7,11,13,17,19,23,29,31,37}, 266112, 0x45e19aaf284f0c4dULL },
    { "KT22_P0", 12, {2,3,5,7,11,13,17,19,23,29,31,37},  20196, 0xb8f42d360615bd7dULL },
};

const int kt_canonical_wheel_hashes_count =
    (int)(sizeof(kt_canonical_wheel_hashes) / sizeof(kt_canonical_wheel_hashes[0]));

const kt_canonical_wheel_t *kt_wheel_canonical_lookup(
    const char *pattern_name,
    const uint32_t *prime_list, int n_primes) {
    if (!pattern_name || !prime_list || n_primes <= 0) return NULL;
    for (int i = 0; i < kt_canonical_wheel_hashes_count; i++) {
        const kt_canonical_wheel_t *e = &kt_canonical_wheel_hashes[i];
        if (!e->pattern_name) continue;
        if (strcmp(e->pattern_name, pattern_name) != 0) continue;
        if (e->n_primes != n_primes) continue;
        int match = 1;
        for (int j = 0; j < n_primes; j++) {
            if (e->primes[j] != prime_list[j]) { match = 0; break; }
        }
        if (match) return e;
    }
    return NULL;
}

/* ─────────────────────────────────────────────────────────────────────────── */
/* Phase 3c: canonical filter-mask hash table.                                */
/* Generated by tools/dump_filter_mask_hashes.gp; same paste-in discipline.   */
/*   L2 primes:     {41, 43, 47, 53, 59, 61}            (6  u64s)             */
/*   ext-L2 primes: {67, 71, 73, 79, 83, 89, 97}        (14 u64s, lo/hi)      */
/*   line primes:   125 primes 101..863, packed 14 u64  (1750 u64s)           */
/* ─────────────────────────────────────────────────────────────────────────── */
const kt_canonical_filter_t kt_canonical_filter_hashes[] = {
    { "KT19_P0", 0x64b1b1c608b2a2afULL, 0x111ec7a7d41a3a65ULL, 0x4162e7e06cd54766ULL },
    { "KT22_P0", 0x62fbf15caf461ed2ULL, 0x09197c3587939f74ULL, 0xb79f912f21732c2aULL },
};

const int kt_canonical_filter_hashes_count =
    (int)(sizeof(kt_canonical_filter_hashes) / sizeof(kt_canonical_filter_hashes[0]));

const kt_canonical_filter_t *kt_filter_canonical_lookup(const char *pattern_name) {
    if (!pattern_name) return NULL;
    for (int i = 0; i < kt_canonical_filter_hashes_count; i++) {
        const kt_canonical_filter_t *e = &kt_canonical_filter_hashes[i];
        if (e->pattern_name && strcmp(e->pattern_name, pattern_name) == 0) return e;
    }
    return NULL;
}
