#!/usr/bin/env python3
# Copyright (c) 2026 Nenad Mićić <nenad@micic.be>
# SPDX-License-Identifier: Apache-2.0
"""Phase 3m-G F1 — Futamura-2 specialization codegen.

Emits a header with baked forbidden-residue masks for one (pattern, primorial)
tuple. The header is consumed by kt_filter_v5_f1.cu's startup-time validator,
which proves the codegen pipeline is correct. The kernel itself still reads
from __constant__ memory in this partial — turning these constants into true
SASS immediate operands requires a full kernel-unroll rewrite that the brief
puts out of scope.

Mirrors kt_forbidden_mask_{u64,u128,packed} from src/cuda/kt_wheel.c verbatim.
"""

KT19_P0_OFFSETS = (0, 4, 6, 10, 12, 16, 24, 30, 34, 40, 42, 46, 52, 54, 60, 66, 70, 72, 76)

L2_PRIMES = (41, 43, 47, 53, 59, 61)
EXT_L2_PRIMES = (67, 71, 73, 79, 83, 89, 97)
LINE_PRIMES = (
    101, 103, 107, 109, 113, 127, 131, 137, 139, 149,
    151, 157, 163, 167, 173, 179, 181, 191, 193, 197,
    199, 211, 223, 227, 229, 233, 239, 241, 251, 257,
    263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
    317, 331, 337, 347, 349, 353, 359, 367, 373, 379,
    383, 389, 397, 401, 409, 419, 421, 431, 433, 439,
    443, 449, 457, 461, 463, 467, 479, 487, 491, 499,
    503, 509, 521, 523, 541, 547, 557, 563, 569, 571,
    577, 587, 593, 599, 601, 607, 613, 617, 619, 631,
    641, 643, 647, 653, 659, 661, 673, 677, 683, 691,
    701, 709, 719, 727, 733, 739, 743, 751, 757, 761,
    769, 773, 787, 797, 809, 811, 821, 823, 827, 829,
    839, 853, 857, 859, 863,
)
KT_LINE_KILL_WORDS = 14


def forbidden_mask_u64(pat, q):
    m = 0
    for b in pat:
        r = (q - (b % q)) % q
        m |= 1 << r
    return m & ((1 << 64) - 1)


def forbidden_mask_u128(pat, q):
    lo, hi = 0, 0
    for b in pat:
        r = (q - (b % q)) % q
        if r < 64:
            lo |= 1 << r
        else:
            hi |= 1 << (r - 64)
    return lo, hi


def forbidden_mask_packed(pat, q, words):
    out = [0] * words
    for b in pat:
        r = (q - (b % q)) % q
        out[r >> 6] |= 1 << (r & 63)
    return out


def emit():
    pat = KT19_P0_OFFSETS
    lines = []
    lines.append("/* Copyright (c) 2026 Nenad Mićić <nenad@micic.be>")
    lines.append(" * SPDX-License-Identifier: Apache-2.0 */")
    lines.append("/* AUTO-GENERATED by tools/gen_f1_baked.py — DO NOT EDIT BY HAND. */")
    lines.append("/* Phase 3m-G F1 Futamura-2 specialization for KT19_P0 / 37# primorial. */")
    lines.append("/* Mirrors kt_forbidden_mask_{u64,u128,packed} for offsets:             */")
    lines.append(f"/*   {pat}  (k={len(pat)}, diam={pat[-1]})                              */")
    lines.append("#ifndef KT_FILTER_V5_F1_BAKED_H")
    lines.append("#define KT_FILTER_V5_F1_BAKED_H")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* L2 (q < 64): single u64 mask per prime. */")
    lines.append(f"static const uint64_t kt_f1_baked_l2_mask[{len(L2_PRIMES)}] = {{")
    for q in L2_PRIMES:
        m = forbidden_mask_u64(pat, q)
        lines.append(f"    0x{m:016x}ULL, /* q={q} */")
    lines.append("};")
    lines.append("")
    lines.append("/* ext-L2 (q < 128): lo/hi u64 pair per prime. */")
    lines.append(f"static const uint64_t kt_f1_baked_ext_l2_lo[{len(EXT_L2_PRIMES)}] = {{")
    for q in EXT_L2_PRIMES:
        lo, _ = forbidden_mask_u128(pat, q)
        lines.append(f"    0x{lo:016x}ULL, /* q={q} lo */")
    lines.append("};")
    lines.append(f"static const uint64_t kt_f1_baked_ext_l2_hi[{len(EXT_L2_PRIMES)}] = {{")
    for q in EXT_L2_PRIMES:
        _, hi = forbidden_mask_u128(pat, q)
        lines.append(f"    0x{hi:016x}ULL, /* q={q} hi */")
    lines.append("};")
    lines.append("")
    lines.append("/* Line-sieve (101..863): 14 u64 words per prime. */")
    lines.append(
        f"static const uint64_t kt_f1_baked_line_kill[{len(LINE_PRIMES)} * {KT_LINE_KILL_WORDS}] = {{"
    )
    for q in LINE_PRIMES:
        words = forbidden_mask_packed(pat, q, KT_LINE_KILL_WORDS)
        cells = ", ".join(f"0x{w:016x}ULL" for w in words)
        lines.append(f"    {cells}, /* q={q} */")
    lines.append("};")
    lines.append("")
    lines.append(f"#define KT_F1_BAKED_L2_COUNT     {len(L2_PRIMES)}")
    lines.append(f"#define KT_F1_BAKED_EXT_L2_COUNT {len(EXT_L2_PRIMES)}")
    lines.append(f"#define KT_F1_BAKED_LINE_COUNT   {len(LINE_PRIMES)}")
    lines.append(f"#define KT_F1_BAKED_LINE_WORDS   {KT_LINE_KILL_WORDS}")
    lines.append("")
    lines.append("#endif /* KT_FILTER_V5_F1_BAKED_H */")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import sys
    out = emit()
    if len(sys.argv) > 1 and sys.argv[1] == "-":
        sys.stdout.write(out)
    else:
        path = sys.argv[1] if len(sys.argv) > 1 else "src/cuda/kt_filter_v5_f1_baked.h"
        with open(path, "w") as f:
            f.write(out)
        sys.stderr.write(f"wrote {path} ({len(out)} bytes)\n")
